# Generated by Django 3.1.7 on 2021-03-16 17:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('time_zone', models.CharField(choices=[('PST', 'Pacific Time'), ('MST', 'Mountain Time'), ('CT', 'Central Time'), ('ET', 'Eastern Time'), ('HST', 'Hawaii Standard Time')], default='PST', max_length=3)),
                ('description', models.CharField(max_length=300)),
                ('speaker', models.CharField(max_length=50)),
                ('location_link', models.CharField(max_length=250)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
